services:
  mysql:
    image: mysql:8.0
    environment:
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
      MYSQL_DATABASE: ${MYSQL_DATABASE}
      MYSQL_USER: ${MYSQL_USER}
      MYSQL_PASSWORD: ${MYSQL_PASSWORD}
    ports:
      - "${MYSQL_PORT_LOCAL}:${MYSQL_PORT}"
    volumes:
      - ./.db:/var/lib/mysql

  migrator:
    build:
      context: .
      dockerfile: docker/local/Dockerfile.backend
    environment:
      MYSQL_HOST: mysql
      MYSQL_PORT: ${MYSQL_PORT}
    depends_on:
      - mysql
    entrypoint: ["/bin/bash", "/shell/migrate-db.sh"]

  backend:
    build:
      context: .
      dockerfile: docker/local/Dockerfile.backend
    environment:
      MYSQL_HOST: mysql
    depends_on:
      - migrator
    ports:
      - "${BACKEND_PORT}:${BACKEND_PORT}"
    entrypoint:
      [
        "gunicorn",
        "src.main:app",
        "-k",
        "uvicorn.workers.UvicornWorker",
        "--workers",
        "1",
        "--bind",
        "0.0.0.0:${BACKEND_PORT}",
      ]

  backend-dev:
    build:
      context: .
      dockerfile: docker/local/Dockerfile.backend
    environment:
      MYSQL_HOST: mysql
    depends_on:
      - migrator
    ports:
      - "${BACKEND_PORT}:${BACKEND_PORT}"
    entrypoint:
      [
        "uvicorn",
        "src.main:app",
        "--reload",
        "--host",
        "0.0.0.0",
        "--port",
        "${BACKEND_PORT}",
      ]
    volumes:
      - ./backend/src:/backend/src

  frontend:
    build:
      context: .
      dockerfile: docker/local/Dockerfile.frontend
    ports:
      - "${FRONTEND_PORT}:${FRONTEND_PORT}"
    develop:
      watch:
        - action: sync
          path: ./frontend
          target: /frontend
          ignore: 
           - node_modules/
        - action: rebuild
          path: ./frontend/package.json
    entrypoint: ["bun", "run", "dev", "--host"]
