FROM python:3.13.3

# Set working directory
WORKDIR /app

COPY ./backend backend
ENV PYTHONPATH=backend

RUN apt-get update && apt-get install -y default-mysql-client

RUN pip install --upgrade pip
RUN pip install --no-cache-dir -r backend/requirements.txt


# entrypoint for migration docker
COPY ./shell/migrate-db.sh shell/migrate-db.sh


# Default command just sleeps (we override it in entrypoint)
CMD ["sleep", "infinity"]
