"""add index

Revision ID: 106153bc4476
Revises: 8fcd673557b0
Create Date: 2025-06-27 19:05:45.008493

"""

from typing import Sequence, Union

import sqlalchemy as sa
from alembic import op
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision: str = "106153bc4476"
down_revision: Union[str, None] = "8fcd673557b0"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index(
        op.f("ix_agent_base_createdAt"), "agent_base", ["createdAt"], unique=False
    )
    op.create_index(
        op.f("ix_agent_base_updatedAt"), "agent_base", ["updatedAt"], unique=False
    )
    op.create_index(
        op.f("ix_agent_node_agentBaseId"), "agent_node", ["agentBaseId"], unique=False
    )
    op.create_index(
        op.f("ix_agent_node_createdAt"), "agent_node", ["createdAt"], unique=False
    )
    op.create_index(
        op.f("ix_agent_node_updatedAt"), "agent_node", ["updatedAt"], unique=False
    )
    op.create_index(op.f("ix_edge_createdAt"), "edge", ["createdAt"], unique=False)
    op.create_index(op.f("ix_edge_fromNodeId"), "edge", ["fromNodeId"], unique=False)
    op.create_index(op.f("ix_edge_toNodeId"), "edge", ["toNodeId"], unique=False)
    op.create_index(op.f("ix_edge_updatedAt"), "edge", ["updatedAt"], unique=False)
    op.drop_column("edge", "name")
    op.create_index(
        op.f("ix_node_agent_node_id"), "node", ["agent_node_id"], unique=False
    )
    op.create_index(op.f("ix_node_createdAt"), "node", ["createdAt"], unique=False)
    op.create_index(op.f("ix_node_type"), "node", ["type"], unique=False)
    op.create_index(op.f("ix_node_updatedAt"), "node", ["updatedAt"], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f("ix_node_updatedAt"), table_name="node")
    op.drop_index(op.f("ix_node_type"), table_name="node")
    op.drop_index(op.f("ix_node_createdAt"), table_name="node")
    op.drop_index(op.f("ix_node_agent_node_id"), table_name="node")
    op.add_column("edge", sa.Column("name", mysql.VARCHAR(length=255), nullable=False))
    op.drop_index(op.f("ix_edge_updatedAt"), table_name="edge")
    op.drop_index(op.f("ix_edge_toNodeId"), table_name="edge")
    op.drop_index(op.f("ix_edge_fromNodeId"), table_name="edge")
    op.drop_index(op.f("ix_edge_createdAt"), table_name="edge")
    op.drop_index(op.f("ix_agent_node_updatedAt"), table_name="agent_node")
    op.drop_index(op.f("ix_agent_node_createdAt"), table_name="agent_node")
    op.drop_index(op.f("ix_agent_node_agentBaseId"), table_name="agent_node")
    op.drop_index(op.f("ix_agent_base_updatedAt"), table_name="agent_base")
    op.drop_index(op.f("ix_agent_base_createdAt"), table_name="agent_base")
    # ### end Alembic commands ###
