"""add custom prompt and model to agent node

Revision ID: 11cf67516030
Revises: 6902a09b49e8
Create Date: 2025-06-29 22:09:49.131619

"""

from typing import Sequence, Union

import sqlalchemy as sa
from alembic import op
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision: str = "11cf67516030"
down_revision: Union[str, None] = "6902a09b49e8"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "agent_node", sa.Column("customModel", sa.VARCHAR(length=255), nullable=True)
    )
    op.add_column("agent_node", sa.Column("customPrompt", sa.TEXT(), nullable=True))
    op.drop_column("agent_node", "prompt")
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("agent_node", sa.Column("prompt", mysql.TEXT(), nullable=True))
    op.drop_column("agent_node", "customPrompt")
    op.drop_column("agent_node", "customModel")
    # ### end Alembic commands ###
