"""node edge agentnode agentbase tables

Revision ID: 2c873b14cf75
Revises:
Create Date: 2025-06-26 17:08:50.995715

"""

from typing import Sequence, Union

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = "2c873b14cf75"
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "agent_base",
        sa.Column("id", sa.VARCHAR(length=255), nullable=False),
        sa.Column("name", sa.VARCHAR(length=255), nullable=False),
        sa.Column("basePrompt", sa.TEXT(), nullable=False),
        sa.Column(
            "createdAt",
            sa.DATETIME(),
            server_default=sa.text("CURRENT_TIMESTAMP"),
            nullable=False,
        ),
        sa.Column(
            "updatedAt",
            sa.DATETIME(),
            server_default=sa.text("CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP"),
            nullable=False,
        ),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("name"),
    )
    op.create_table(
        "agent_node",
        sa.Column("id", sa.VARCHAR(length=255), nullable=False),
        sa.Column("name", sa.VARCHAR(length=255), nullable=False),
        sa.Column("agentBaseId", sa.VARCHAR(length=255), nullable=False),
        sa.Column("prompt", sa.TEXT(), nullable=True),
        sa.Column(
            "createdAt",
            sa.DATETIME(),
            server_default=sa.text("CURRENT_TIMESTAMP"),
            nullable=False,
        ),
        sa.Column(
            "updatedAt",
            sa.DATETIME(),
            server_default=sa.text("CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(
            ["agentBaseId"],
            ["agent_base.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_table(
        "node",
        sa.Column("id", sa.VARCHAR(length=255), nullable=False),
        sa.Column("type", sa.VARCHAR(length=255), nullable=False),
        sa.Column("agent_node_id", sa.VARCHAR(length=255), nullable=True),
        sa.Column(
            "createdAt",
            sa.DATETIME(),
            server_default=sa.text("CURRENT_TIMESTAMP"),
            nullable=False,
        ),
        sa.Column(
            "updatedAt",
            sa.DATETIME(),
            server_default=sa.text("CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(
            ["agent_node_id"],
            ["agent_node.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_table(
        "edge",
        sa.Column("id", sa.VARCHAR(length=255), nullable=False),
        sa.Column("name", sa.VARCHAR(length=255), nullable=False),
        sa.Column("fromNodeId", sa.VARCHAR(length=255), nullable=False),
        sa.Column("toNodeId", sa.VARCHAR(length=255), nullable=False),
        sa.Column(
            "createdAt",
            sa.DATETIME(),
            server_default=sa.text("CURRENT_TIMESTAMP"),
            nullable=False,
        ),
        sa.Column(
            "updatedAt",
            sa.DATETIME(),
            server_default=sa.text("CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(
            ["fromNodeId"],
            ["node.id"],
        ),
        sa.ForeignKeyConstraint(
            ["toNodeId"],
            ["node.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("edge")
    op.drop_table("node")
    op.drop_table("agent_node")
    op.drop_table("agent_base")
    # ### end Alembic commands ###
