"""add prompts and model to agents

Revision ID: 3b48363ac9af
Revises: 6902a09b49e8
Create Date: 2025-06-29 21:06:44.035752

"""

from typing import Sequence, Union

import sqlalchemy as sa
from alembic import op
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision: str = "3b48363ac9af"
down_revision: Union[str, None] = "6902a09b49e8"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "agent_base", sa.Column("baseModel", sa.VARCHAR(length=255), nullable=False)
    )
    op.add_column("agent_base", sa.Column("basePrompt", sa.TEXT(), nullable=False))
    op.add_column(
        "agent_node", sa.Column("customModel", sa.VARCHAR(length=255), nullable=True)
    )
    op.add_column("agent_node", sa.Column("customPrompt", sa.TEXT(), nullable=True))
    op.drop_column("agent_node", "prompt")
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("agent_node", sa.Column("prompt", mysql.TEXT(), nullable=True))
    op.drop_column("agent_node", "customPrompt")
    op.drop_column("agent_node", "customModel")
    op.drop_column("agent_base", "basePrompt")
    op.drop_column("agent_base", "baseModel")
    # ### end Alembic commands ###
