"""add isBaseEntryPoin on node

Revision ID: 6902a09b49e8
Revises: f74cea247275
Create Date: 2025-06-28 16:07:42.195944

"""

from typing import Sequence, Union

import sqlalchemy as sa
from alembic import op
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision: str = "6902a09b49e8"
down_revision: Union[str, None] = "f74cea247275"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "node",
        sa.Column(
            "isBaseEntryPoint",
            mysql.TINYINT(display_width=1),
            server_default="0",
            nullable=False,
        ),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("node", "isBaseEntryPoint")
    # ### end Alembic commands ###
