"""add traceparent for logfire in conversation

Revision ID: 6f4e3f0736ad
Revises: e50cfc6c928f
Create Date: 2025-08-05 20:44:08.696900

"""

from typing import Sequence, Union

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = "6f4e3f0736ad"
down_revision: Union[str, None] = "e50cfc6c928f"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "conversation",
        sa.Column(
            "traceParent",
            sa.VARCHAR(length=255),
            server_default="default",
            nullable=False,
        ),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("conversation", "traceParent")
    # ### end Alembic commands ###
