"""add name to user

Revision ID: a6c2d8f7f4e7
Revises: eac548355b6a
Create Date: 2025-07-21 18:38:07.847655

"""

from typing import Sequence, Union

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = "a6c2d8f7f4e7"
down_revision: Union[str, None] = "eac548355b6a"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("user", sa.Column("name", sa.VARCHAR(length=255), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("user", "name")
    # ### end Alembic commands ###
