"""graph state table

Revision ID: e50cfc6c928f
Revises: a6c2d8f7f4e7
Create Date: 2025-07-21 20:13:38.515250

"""

from typing import Sequence, Union

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = "e50cfc6c928f"
down_revision: Union[str, None] = "a6c2d8f7f4e7"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "graph_state",
        sa.Column("message_history", sa.TEXT(), nullable=False),
        sa.Column("graphId", sa.VARCHAR(length=255), nullable=False),
        sa.Column("entryNodeId", sa.VARCHAR(length=255), nullable=False),
        sa.Column("conversationId", sa.VARCHAR(length=255), nullable=False),
        sa.Column("userId", sa.VARCHAR(length=255), nullable=False),
        sa.Column("id", sa.VARCHAR(length=255), nullable=False),
        sa.Column(
            "createdAt",
            sa.DATETIME(),
            server_default=sa.text("CURRENT_TIMESTAMP"),
            nullable=False,
        ),
        sa.Column(
            "updatedAt",
            sa.DATETIME(),
            server_default=sa.text("CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(
            ["conversationId"],
            ["conversation.id"],
        ),
        sa.ForeignKeyConstraint(
            ["entryNodeId"],
            ["node.id"],
        ),
        sa.ForeignKeyConstraint(
            ["graphId"],
            ["graph.id"],
        ),
        sa.ForeignKeyConstraint(
            ["userId"],
            ["user.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        op.f("ix_graph_state_conversationId"),
        "graph_state",
        ["conversationId"],
        unique=False,
    )
    op.create_index(
        op.f("ix_graph_state_createdAt"), "graph_state", ["createdAt"], unique=False
    )
    op.create_index(
        op.f("ix_graph_state_updatedAt"), "graph_state", ["updatedAt"], unique=False
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f("ix_graph_state_updatedAt"), table_name="graph_state")
    op.drop_index(op.f("ix_graph_state_createdAt"), table_name="graph_state")
    op.drop_index(op.f("ix_graph_state_conversationId"), table_name="graph_state")
    op.drop_table("graph_state")
    # ### end Alembic commands ###
