"""expense and conv table

Revision ID: eac548355b6a
Revises: f2cbb3c1feda
Create Date: 2025-07-19 15:02:13.999313

"""

from typing import Sequence, Union

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = "eac548355b6a"
down_revision: Union[str, None] = "f2cbb3c1feda"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "conversation",
        sa.Column("graphId", sa.VARCHAR(length=255), nullable=False),
        sa.Column("userId", sa.VARCHAR(length=255), nullable=True),
        sa.Column("id", sa.VARCHAR(length=255), nullable=False),
        sa.Column(
            "createdAt",
            sa.DATETIME(),
            server_default=sa.text("CURRENT_TIMESTAMP"),
            nullable=False,
        ),
        sa.Column(
            "updatedAt",
            sa.DATETIME(),
            server_default=sa.text("CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(
            ["graphId"],
            ["graph.id"],
        ),
        sa.ForeignKeyConstraint(
            ["userId"],
            ["user.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        op.f("ix_conversation_createdAt"), "conversation", ["createdAt"], unique=False
    )
    op.create_index(
        op.f("ix_conversation_graphId"), "conversation", ["graphId"], unique=False
    )
    op.create_index(
        op.f("ix_conversation_updatedAt"), "conversation", ["updatedAt"], unique=False
    )
    op.create_index(
        op.f("ix_conversation_userId"), "conversation", ["userId"], unique=False
    )
    op.create_table(
        "expense",
        sa.Column("cost", sa.DECIMAL(precision=11, scale=8), nullable=False),
        sa.Column("graphId", sa.VARCHAR(length=255), nullable=False),
        sa.Column("nodeId", sa.VARCHAR(length=255), nullable=False),
        sa.Column("source", sa.VARCHAR(length=255), nullable=False),
        sa.Column("conversationId", sa.VARCHAR(length=255), nullable=False),
        sa.Column("userId", sa.VARCHAR(length=255), nullable=True),
        sa.Column("id", sa.VARCHAR(length=255), nullable=False),
        sa.Column(
            "createdAt",
            sa.DATETIME(),
            server_default=sa.text("CURRENT_TIMESTAMP"),
            nullable=False,
        ),
        sa.Column(
            "updatedAt",
            sa.DATETIME(),
            server_default=sa.text("CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(
            ["conversationId"],
            ["conversation.id"],
        ),
        sa.ForeignKeyConstraint(
            ["graphId"],
            ["graph.id"],
        ),
        sa.ForeignKeyConstraint(
            ["nodeId"],
            ["node.id"],
        ),
        sa.ForeignKeyConstraint(
            ["userId"],
            ["user.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        op.f("ix_expense_conversationId"), "expense", ["conversationId"], unique=False
    )
    op.create_index(
        op.f("ix_expense_createdAt"), "expense", ["createdAt"], unique=False
    )
    op.create_index(op.f("ix_expense_graphId"), "expense", ["graphId"], unique=False)
    op.create_index(op.f("ix_expense_nodeId"), "expense", ["nodeId"], unique=False)
    op.create_index(op.f("ix_expense_source"), "expense", ["source"], unique=False)
    op.create_index(
        op.f("ix_expense_updatedAt"), "expense", ["updatedAt"], unique=False
    )
    op.create_index(op.f("ix_expense_userId"), "expense", ["userId"], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f("ix_expense_userId"), table_name="expense")
    op.drop_index(op.f("ix_expense_updatedAt"), table_name="expense")
    op.drop_index(op.f("ix_expense_source"), table_name="expense")
    op.drop_index(op.f("ix_expense_nodeId"), table_name="expense")
    op.drop_index(op.f("ix_expense_graphId"), table_name="expense")
    op.drop_index(op.f("ix_expense_createdAt"), table_name="expense")
    op.drop_index(op.f("ix_expense_conversationId"), table_name="expense")
    op.drop_table("expense")
    op.drop_index(op.f("ix_conversation_userId"), table_name="conversation")
    op.drop_index(op.f("ix_conversation_updatedAt"), table_name="conversation")
    op.drop_index(op.f("ix_conversation_graphId"), table_name="conversation")
    op.drop_index(op.f("ix_conversation_createdAt"), table_name="conversation")
    op.drop_table("conversation")
    # ### end Alembic commands ###
