"""remove agent base table

Revision ID: f2cbb3c1feda
Revises: 11cf67516030
Create Date: 2025-06-30 19:44:14.916439

"""

from typing import Sequence, Union

import sqlalchemy as sa
from alembic import op
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision: str = "f2cbb3c1feda"
down_revision: Union[str, None] = "11cf67516030"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint("agent_node_ibfk_1", "agent_node", type_="foreignkey")
    op.drop_index("ix_agent_node_agentBaseId", table_name="agent_node")
    op.drop_index("ix_agent_base_createdAt", table_name="agent_base")
    op.drop_index("ix_agent_base_updatedAt", table_name="agent_base")
    op.drop_index("name", table_name="agent_base")
    op.drop_table("agent_base")
    op.add_column(
        "agent_node", sa.Column("agentBaseName", sa.VARCHAR(length=255), nullable=False)
    )
    op.create_index(
        op.f("ix_agent_node_agentBaseName"),
        "agent_node",
        ["agentBaseName"],
        unique=False,
    )
    op.drop_column("agent_node", "agentBaseId")
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "agent_node",
        sa.Column("agentBaseId", mysql.VARCHAR(length=255), nullable=False),
    )
    op.drop_index(op.f("ix_agent_node_agentBaseName"), table_name="agent_node")
    op.drop_column("agent_node", "agentBaseName")
    op.create_table(
        "agent_base",
        sa.Column("name", mysql.VARCHAR(length=255), nullable=False),
        sa.Column("id", mysql.VARCHAR(length=255), nullable=False),
        sa.Column(
            "createdAt",
            mysql.DATETIME(),
            server_default=sa.text("CURRENT_TIMESTAMP"),
            nullable=False,
        ),
        sa.Column(
            "updatedAt",
            mysql.DATETIME(),
            server_default=sa.text("CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP"),
            nullable=False,
        ),
        sa.PrimaryKeyConstraint("id"),
        mysql_collate="utf8mb4_0900_ai_ci",
        mysql_default_charset="utf8mb4",
        mysql_engine="InnoDB",
    )
    op.create_index("name", "agent_base", ["name"], unique=True)
    op.create_index(
        "ix_agent_base_updatedAt", "agent_base", ["updatedAt"], unique=False
    )
    op.create_index(
        "ix_agent_base_createdAt", "agent_base", ["createdAt"], unique=False
    )
    op.create_index(
        "ix_agent_node_agentBaseId", "agent_node", ["agentBaseId"], unique=False
    )
    op.create_foreign_key(
        "agent_node_ibfk_1", "agent_node", "agent_base", ["agentBaseId"], ["id"]
    )
    # ### end Alembic commands ###
