"""init db with base tables

Revision ID: f74cea247275
Revises:
Create Date: 2025-06-27 20:01:02.064991

"""

from typing import Sequence, Union

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = "f74cea247275"
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "agent_base",
        sa.Column("name", sa.VARCHAR(length=255), nullable=False),
        sa.Column("id", sa.VARCHAR(length=255), nullable=False),
        sa.Column(
            "createdAt",
            sa.DATETIME(),
            server_default=sa.text("CURRENT_TIMESTAMP"),
            nullable=False,
        ),
        sa.Column(
            "updatedAt",
            sa.DATETIME(),
            server_default=sa.text("CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP"),
            nullable=False,
        ),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("name"),
    )
    op.create_index(
        op.f("ix_agent_base_createdAt"), "agent_base", ["createdAt"], unique=False
    )
    op.create_index(
        op.f("ix_agent_base_updatedAt"), "agent_base", ["updatedAt"], unique=False
    )
    op.create_table(
        "user",
        sa.Column("id", sa.VARCHAR(length=255), nullable=False),
        sa.Column(
            "createdAt",
            sa.DATETIME(),
            server_default=sa.text("CURRENT_TIMESTAMP"),
            nullable=False,
        ),
        sa.Column(
            "updatedAt",
            sa.DATETIME(),
            server_default=sa.text("CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP"),
            nullable=False,
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(op.f("ix_user_createdAt"), "user", ["createdAt"], unique=False)
    op.create_index(op.f("ix_user_updatedAt"), "user", ["updatedAt"], unique=False)
    op.create_table(
        "graph",
        sa.Column("name", sa.VARCHAR(length=255), nullable=False),
        sa.Column("userId", sa.VARCHAR(length=255), nullable=False),
        sa.Column("id", sa.VARCHAR(length=255), nullable=False),
        sa.Column(
            "createdAt",
            sa.DATETIME(),
            server_default=sa.text("CURRENT_TIMESTAMP"),
            nullable=False,
        ),
        sa.Column(
            "updatedAt",
            sa.DATETIME(),
            server_default=sa.text("CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(
            ["userId"],
            ["user.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(op.f("ix_graph_createdAt"), "graph", ["createdAt"], unique=False)
    op.create_index(op.f("ix_graph_updatedAt"), "graph", ["updatedAt"], unique=False)
    op.create_index(op.f("ix_graph_userId"), "graph", ["userId"], unique=False)
    op.create_table(
        "agent_node",
        sa.Column("name", sa.VARCHAR(length=255), nullable=False),
        sa.Column("agentBaseId", sa.VARCHAR(length=255), nullable=False),
        sa.Column("prompt", sa.TEXT(), nullable=True),
        sa.Column("userId", sa.VARCHAR(length=255), nullable=False),
        sa.Column("graphId", sa.VARCHAR(length=255), nullable=False),
        sa.Column("id", sa.VARCHAR(length=255), nullable=False),
        sa.Column(
            "createdAt",
            sa.DATETIME(),
            server_default=sa.text("CURRENT_TIMESTAMP"),
            nullable=False,
        ),
        sa.Column(
            "updatedAt",
            sa.DATETIME(),
            server_default=sa.text("CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(
            ["agentBaseId"],
            ["agent_base.id"],
        ),
        sa.ForeignKeyConstraint(
            ["graphId"],
            ["graph.id"],
        ),
        sa.ForeignKeyConstraint(
            ["userId"],
            ["user.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        op.f("ix_agent_node_agentBaseId"), "agent_node", ["agentBaseId"], unique=False
    )
    op.create_index(
        op.f("ix_agent_node_createdAt"), "agent_node", ["createdAt"], unique=False
    )
    op.create_index(
        op.f("ix_agent_node_graphId"), "agent_node", ["graphId"], unique=False
    )
    op.create_index(
        op.f("ix_agent_node_updatedAt"), "agent_node", ["updatedAt"], unique=False
    )
    op.create_index(
        op.f("ix_agent_node_userId"), "agent_node", ["userId"], unique=False
    )
    op.create_table(
        "node",
        sa.Column("type", sa.VARCHAR(length=255), nullable=False),
        sa.Column("agentNodeId", sa.VARCHAR(length=255), nullable=True),
        sa.Column("graphId", sa.VARCHAR(length=255), nullable=False),
        sa.Column("id", sa.VARCHAR(length=255), nullable=False),
        sa.Column(
            "createdAt",
            sa.DATETIME(),
            server_default=sa.text("CURRENT_TIMESTAMP"),
            nullable=False,
        ),
        sa.Column(
            "updatedAt",
            sa.DATETIME(),
            server_default=sa.text("CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(
            ["agentNodeId"],
            ["agent_node.id"],
        ),
        sa.ForeignKeyConstraint(
            ["graphId"],
            ["graph.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(op.f("ix_node_createdAt"), "node", ["createdAt"], unique=False)
    op.create_index(op.f("ix_node_graphId"), "node", ["graphId"], unique=False)
    op.create_index(op.f("ix_node_type"), "node", ["type"], unique=False)
    op.create_index(op.f("ix_node_updatedAt"), "node", ["updatedAt"], unique=False)
    op.create_table(
        "edge",
        sa.Column("fromNodeId", sa.VARCHAR(length=255), nullable=False),
        sa.Column("toNodeId", sa.VARCHAR(length=255), nullable=False),
        sa.Column("graphId", sa.VARCHAR(length=255), nullable=False),
        sa.Column("id", sa.VARCHAR(length=255), nullable=False),
        sa.Column(
            "createdAt",
            sa.DATETIME(),
            server_default=sa.text("CURRENT_TIMESTAMP"),
            nullable=False,
        ),
        sa.Column(
            "updatedAt",
            sa.DATETIME(),
            server_default=sa.text("CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(
            ["fromNodeId"],
            ["node.id"],
        ),
        sa.ForeignKeyConstraint(
            ["graphId"],
            ["graph.id"],
        ),
        sa.ForeignKeyConstraint(
            ["toNodeId"],
            ["node.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(op.f("ix_edge_createdAt"), "edge", ["createdAt"], unique=False)
    op.create_index(op.f("ix_edge_fromNodeId"), "edge", ["fromNodeId"], unique=False)
    op.create_index(op.f("ix_edge_graphId"), "edge", ["graphId"], unique=False)
    op.create_index(op.f("ix_edge_toNodeId"), "edge", ["toNodeId"], unique=False)
    op.create_index(op.f("ix_edge_updatedAt"), "edge", ["updatedAt"], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f("ix_edge_updatedAt"), table_name="edge")
    op.drop_index(op.f("ix_edge_toNodeId"), table_name="edge")
    op.drop_index(op.f("ix_edge_graphId"), table_name="edge")
    op.drop_index(op.f("ix_edge_fromNodeId"), table_name="edge")
    op.drop_index(op.f("ix_edge_createdAt"), table_name="edge")
    op.drop_table("edge")
    op.drop_index(op.f("ix_node_updatedAt"), table_name="node")
    op.drop_index(op.f("ix_node_type"), table_name="node")
    op.drop_index(op.f("ix_node_graphId"), table_name="node")
    op.drop_index(op.f("ix_node_createdAt"), table_name="node")
    op.drop_table("node")
    op.drop_index(op.f("ix_agent_node_userId"), table_name="agent_node")
    op.drop_index(op.f("ix_agent_node_updatedAt"), table_name="agent_node")
    op.drop_index(op.f("ix_agent_node_graphId"), table_name="agent_node")
    op.drop_index(op.f("ix_agent_node_createdAt"), table_name="agent_node")
    op.drop_index(op.f("ix_agent_node_agentBaseId"), table_name="agent_node")
    op.drop_table("agent_node")
    op.drop_index(op.f("ix_graph_userId"), table_name="graph")
    op.drop_index(op.f("ix_graph_updatedAt"), table_name="graph")
    op.drop_index(op.f("ix_graph_createdAt"), table_name="graph")
    op.drop_table("graph")
    op.drop_index(op.f("ix_user_updatedAt"), table_name="user")
    op.drop_index(op.f("ix_user_createdAt"), table_name="user")
    op.drop_table("user")
    op.drop_index(op.f("ix_agent_base_updatedAt"), table_name="agent_base")
    op.drop_index(op.f("ix_agent_base_createdAt"), table_name="agent_base")
    op.drop_table("agent_base")
    # ### end Alembic commands ###
